name: "! AA - MAXLEND VULTURE"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  vulture-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 1. Install
        run: pip install requests boto3 pandas
      - name: 2. Run MaxLend Engine
        run: python article-generator.py
      - name: 3. Save to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "MaxLend Empire Sync"
